### ISSUE TITLE
Seems like switch instance not working without restart

### ISSUE THREAD

**Issue by bschultz** [versx/ControllerJS#11]
Auto assignment was not working so I manually assigned the quest instance. But the device kept scanning pokemon.
Only after ControllerJS restart it begans to run the quest instance

**Comment by versx** [comment]
Switching instances should be fixed in latest now.

**Comment by bschultz** [comment]
Cool, will test later

**Comment by bschultz** [comment]
Sorry for the late response. Looks good now
