### ISSUE TITLE
Duplicate "On Complete" assignment

### ISSUE THREAD

**Issue by bschultz** [versx/ControllerJS#16]
When creating a new assignment with empty time for "on complete" and click the "Create On Complete Auto-Assignment" checkbox, ControllerJS will create two "on complete" assignments.

I think the checkbox is needless

**Comment by versx** [comment]
This is intended behavior, it's more or less used with a time set for the assignment time. I think the best option would be to hide the checkbox if the time value is empty/null.

**Comment by versx** [comment]
Closing as this should replicate what I described above now in https://github.com/versx/ControllerJS/commit/de8673917de4a0a2a413b3527101ec59fd732a0e
